CREATE DATABASE IF NOT EXISTS mood_journal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mood_journal;

CREATE TABLE IF NOT EXISTS entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  emotions JSON NOT NULL,
  top_label VARCHAR(50) NOT NULL,
  top_score DECIMAL(5,4) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
